kind = "web"
previewPath = "/"
title = "Project Handball Shop"
version = "1.0.0"
id = "artifacts/project-handball-shop"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24362

[services.development]
run = "pnpm --filter @workspace/project-handball-shop run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/project-handball-shop", "run", "build" ]
publicDir = "artifacts/project-handball-shop/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24362"
BASE_PATH = "/"
