export type ProductColor = {
  name: string;
  hex: string;
};

export type Product = {
  id: string;
  name: string;
  price: number;
  description: string;
  image: string;
  images: string[];
  colorImages: Record<string, number>;
  sizes: string[];
  colors: ProductColor[];
  category: string;
  isNew?: boolean;
};

function gallery(folder: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `/images/products/${folder}/${i + 1}.jpg`);
}

export const products: Product[] = [
  {
    id: "i-got-next-cotton-tee",
    name: "ProjectHandball X FL Limited Edition Tee",
    price: 35,
    description: "A limited edition collab tee you won't find anywhere else. Premium cotton, bold graphics, and that Project Handball energy. Grab it before it's gone.",
    image: "/images/products/i-got-next-cotton-tee/31.jpg",
    images: gallery("i-got-next-cotton-tee", 36),
    colorImages: {
      "Black":        0,
      "Navy":         3,
      "Safety Green": 6,
      "Orange":       9,
      "Red":          12,
      "Tropical Blue":15,
      "Russet":       18,
      "Purple":       21,
      "Gravel":       24,
      "Irish Green":  27,
      "Light Blue":   30,
      "Light Pink":   33,
    },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Black",         hex: "#1A1A1A" },
      { name: "Navy",          hex: "#1F2A4A" },
      { name: "Safety Green",  hex: "#C8E800" },
      { name: "Orange",        hex: "#E05722" },
      { name: "Red",           hex: "#C0162C" },
      { name: "Tropical Blue", hex: "#0099C0" },
      { name: "Russet",        hex: "#7A3520" },
      { name: "Purple",        hex: "#5B2D82" },
      { name: "Gravel",        hex: "#868A8C" },
      { name: "Irish Green",   hex: "#009A44" },
      { name: "Light Blue",    hex: "#A8CBE2" },
      { name: "Light Pink",    hex: "#F4B8CA" },
    ],
    category: "Tees",
    isNew: true,
  },
  {
    id: "simply-handball-hoodie",
    name: "Simply Handball Hoodie",
    price: 45,
    description: "100% organic cotton hoodie that says exactly what it needs to say. Clean design, premium feel, built for the player who lets their game do the talking.",
    image: "/images/products/simply-handball-hoodie/1.jpg",
    images: gallery("simply-handball-hoodie", 24),
    colorImages: { "Military Green": 0, "Maroon": 2, "Light Blue": 4, "Red": 6, "Purple": 8, "Black": 10, "Carolina Blue": 12, "Irish Green": 14, "Heliconia": 16, "Light Pink": 18, "Gold": 20, "Navy": 22 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Military Green", hex: "#4A5523" },
      { name: "Maroon",         hex: "#7D1B2A" },
      { name: "Light Blue",     hex: "#A8CBE2" },
      { name: "Red",            hex: "#C8102E" },
      { name: "Purple",         hex: "#5B2D82" },
      { name: "Black",          hex: "#1A1A1A" },
      { name: "Carolina Blue",  hex: "#5B9BD5" },
      { name: "Irish Green",    hex: "#009A44" },
      { name: "Heliconia",      hex: "#D63874" },
      { name: "Light Pink",     hex: "#F4B8CA" },
      { name: "Gold",           hex: "#F5A623" },
      { name: "Navy",           hex: "#1F2A4A" },
    ],
    category: "Hoodies",
    isNew: true,
  },
  {
    id: "i-got-next-hoodie",
    name: '"I Got Next." Hoodie',
    price: 45,
    description: "The three words that echo across every handball court. Heavy fleece hoodie with embroidered details. A statement piece for those who are always ready.",
    image: "/images/products/maroon-i-got-next-hoodie/1.jpg",
    images: gallery("maroon-i-got-next-hoodie", 24),
    colorImages: { "Black": 0, "Navy": 2, "Red": 4, "Carolina Blue": 6, "Maroon": 8, "Light Pink": 10, "Irish Green": 12, "White": 14, "Purple": 16, "Heliconia": 18, "Gold": 20, "Light Blue": 22 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Black",         hex: "#1A1A1A" },
      { name: "Navy",          hex: "#1F2A4A" },
      { name: "Red",           hex: "#C8102E" },
      { name: "Carolina Blue", hex: "#5B9BD5" },
      { name: "Maroon",        hex: "#7D1B2A" },
      { name: "Light Pink",    hex: "#F4B8CA" },
      { name: "Irish Green",   hex: "#009A44" },
      { name: "White",         hex: "#F8F8F8" },
      { name: "Purple",        hex: "#5B2D82" },
      { name: "Heliconia",     hex: "#D63874" },
      { name: "Gold",          hex: "#F5A623" },
      { name: "Light Blue",    hex: "#A8CBE2" },
    ],
    category: "Hoodies",
  },
  {
    id: "i-love-handball-hoodie",
    name: "I ♥ Handball Hoodie",
    price: 45,
    description: "For those who don't just play handball — they live it. Cozy heavyweight hoodie with the classic I Love Handball graphic. A gift-ready fan favorite.",
    image: "/images/products/i-3-handball-hoodie/1.jpg",
    images: gallery("i-3-handball-hoodie", 12),
    colorImages: { "White": 0, "Maroon": 2, "Black": 4, "Heliconia": 6, "Light Pink": 8, "Navy": 10 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "White",      hex: "#F8F8F8" },
      { name: "Maroon",     hex: "#7D1B2A" },
      { name: "Black",      hex: "#1A1A1A" },
      { name: "Heliconia",  hex: "#D63874" },
      { name: "Light Pink", hex: "#F4B8CA" },
      { name: "Navy",       hex: "#1F2A4A" },
    ],
    category: "Hoodies",
  },
  {
    id: "rightside-stripe",
    name: "Rightside Hoodie (Stripe)",
    price: 45,
    description: "A bold stripe design that turns heads on and off the court. Heavyweight fleece with a clean cut. Because your warm-up gear should be as sharp as your serve.",
    image: "/images/products/rightside-stripe/1.jpg",
    images: gallery("rightside-stripe", 12),
    colorImages: { "Black": 0, "Navy": 2, "Red": 4, "Light Pink": 6, "Sport Grey": 8, "Light Blue": 10 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Black",      hex: "#1A1A1A" },
      { name: "Navy",       hex: "#1F2A4A" },
      { name: "Red",        hex: "#C8102E" },
      { name: "Light Pink", hex: "#F4B8CA" },
      { name: "Sport Grey", hex: "#A0A0A0" },
      { name: "Light Blue", hex: "#A8CBE2" },
    ],
    category: "Hoodies",
  },
  {
    id: "true-sport-dry-fit",
    name: '"The True Sport" Dry-Fit Tee',
    price: 35,
    description: "Lightweight, breathable dry-fit material built for competitive play. Moisture-wicking fabric keeps you cool when the rallies get long. Represent the truest sport.",
    image: "/images/products/the-true-sport-dry-fit-tee/1.jpg",
    images: gallery("the-true-sport-dry-fit-tee", 8),
    colorImages: { "Sport Red": 0, "Sport Graphite": 2, "Sport Dark Navy": 4, "Black": 6 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Sport Red",       hex: "#C41230" },
      { name: "Sport Graphite",  hex: "#4A4A4A" },
      { name: "Sport Dark Navy", hex: "#0A1433" },
      { name: "Black",           hex: "#1A1A1A" },
    ],
    category: "Tees",
  },
  {
    id: "true-sport-cotton",
    name: '"The True Sport" Cotton Tee',
    price: 25,
    description: "Represent handball and New York culture with this unique cotton tee. Soft, durable, and broken in from day one. A staple for any real one.",
    image: "/images/products/the-true-sport-t-shirt/1.jpg",
    images: gallery("the-true-sport-t-shirt", 22),
    colorImages: { "Royal": 0, "Charcoal": 2, "Light Blue": 4, "Irish Green": 6, "Navy": 8, "Red": 10, "Orange": 12, "Black": 14, "Gold": 16, "Sand": 18, "Natural": 20 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Royal",       hex: "#2255A4" },
      { name: "Charcoal",    hex: "#3B3B3B" },
      { name: "Light Blue",  hex: "#A8CBE2" },
      { name: "Irish Green", hex: "#009A44" },
      { name: "Navy",        hex: "#1F2A4A" },
      { name: "Red",         hex: "#C8102E" },
      { name: "Orange",      hex: "#E35C22" },
      { name: "Black",       hex: "#1A1A1A" },
      { name: "Gold",        hex: "#F5A623" },
      { name: "Sand",        hex: "#C2B280" },
      { name: "Natural",     hex: "#F5F0E8" },
    ],
    category: "Tees",
  },
  {
    id: "where-theres-a-will",
    name: '"Where There\'s A Will" Tee',
    price: 35,
    description: "The mantra of every handball player who ever grinded through a tough match. Heavyweight cotton tee with a motivational graphic that hits every time.",
    image: "/images/products/where-theres-a-will-t-shirt/1.jpg",
    images: gallery("where-theres-a-will-t-shirt", 16),
    colorImages: { "Royal": 0, "Charcoal": 2, "Sky Blue": 4, "Black": 6, "Athletic Navy": 8, "Athletic Heather": 10, "Safety Green": 12, "New Red": 14 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Royal",            hex: "#2255A4" },
      { name: "Charcoal",         hex: "#3B3B3B" },
      { name: "Sky Blue",         hex: "#87CEEB" },
      { name: "Black",            hex: "#1A1A1A" },
      { name: "Athletic Navy",    hex: "#1B2D5A" },
      { name: "Athletic Heather", hex: "#9BA2A9" },
      { name: "Safety Green",     hex: "#C8E800" },
      { name: "New Red",          hex: "#C8102E" },
    ],
    category: "Tees",
  },
  {
    id: "may-the-4th",
    name: "May The 4th Be With You Tee",
    price: 35,
    description: "A crossover classic for the handball player who's also a fan of the galaxy far, far away. Limited seasonal drop. Wear it with pride on and off the court.",
    image: "/images/products/may-the-4th-be-with-you/1.jpg",
    images: gallery("may-the-4th-be-with-you", 8),
    colorImages: { "Black": 0, "Sport Dark Navy": 2, "Sport Graphite": 4, "Sport Red": 6 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Black",           hex: "#1A1A1A" },
      { name: "Sport Dark Navy", hex: "#0A1433" },
      { name: "Sport Graphite",  hex: "#4A4A4A" },
      { name: "Sport Red",       hex: "#C41230" },
    ],
    category: "Tees",
  },
  {
    id: "vlogger-tee",
    name: '"What Are You Wearing?" Tee',
    price: 35,
    description: "For the player documenting the culture. A tongue-in-cheek nod to everyone out here filming every ace and lob shot. Soft cotton, standout graphic.",
    image: "/images/products/what-are-you-wearing-tee/1.jpg",
    images: gallery("what-are-you-wearing-tee", 2),
    colorImages: { "Black": 0, "Safety Orange": 1 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "Black",         hex: "#1A1A1A" },
      { name: "Safety Orange", hex: "#FF6700" },
    ],
    category: "Tees",
  },
  {
    id: "pink-dry-fit-tank",
    name: 'Pink "I Got Next." Dry-Fit Tank',
    price: 35,
    description: "Sleek pink dry-fit tank for the player who stays fresh under pressure. Moisture-wicking, lightweight, and built for full range of motion. Court-ready from the jump.",
    image: "/images/products/pink-i-got-next-dry-fit-jersey/1.jpg",
    images: gallery("pink-i-got-next-dry-fit-jersey", 2),
    colorImages: { "Pink": 0 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [{ name: "Pink", hex: "#FFA0B4" }],
    category: "Tanks",
  },
  {
    id: "black-dry-fit-tank",
    name: 'Black "I Got Next." Dry-Fit Tank',
    price: 35,
    description: "The classic in black. Dry-fit performance tank that moves with you. Clean, minimal, and unmistakably Project Handball. A wardrobe essential for any player.",
    image: "/images/products/black-i-got-next-dry-fit-jersey/1.jpg",
    images: gallery("black-i-got-next-dry-fit-jersey", 2),
    colorImages: { "Black": 0 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    category: "Tanks",
  },
  {
    id: "red-dry-fit-tank",
    name: 'Red "I Got Next." Dry-Fit Tank',
    price: 35,
    description: "Bold red colorway for players who want to be seen. Same performance dry-fit build — moisture-wicking, breathable, competition-ready on any court.",
    image: "/images/products/red-i-got-next-v-neck-jersey/1.jpg",
    images: gallery("red-i-got-next-v-neck-jersey", 2),
    colorImages: { "Red": 0 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [{ name: "Red", hex: "#C8102E" }],
    category: "Tanks",
  },
  {
    id: "blue-dry-fit-tank",
    name: 'Blue "I Got Next." Dry-Fit Tank',
    price: 35,
    description: "Sky blue dry-fit tank for the warm weather grinder. Lightweight performance fabric keeps you cool when the sun is beating down and the rallies keep coming.",
    image: "/images/products/blue-i-got-next-v-neck-jersey/1.jpg",
    images: gallery("blue-i-got-next-v-neck-jersey", 2),
    colorImages: { "Blue": 0 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [{ name: "Blue", hex: "#3BB7FD" }],
    category: "Tanks",
  },
  {
    id: "grey-dry-fit-tank",
    name: 'Grey "I Got Next." Dry-Fit Tank',
    price: 35,
    description: "The clean grey colorway for the understated player who lets their game speak loudest. Dry-fit performance with the iconic I Got Next. graphic.",
    image: "/images/products/grey-i-got-next-dry-fit-jersey/1.jpg",
    images: gallery("grey-i-got-next-dry-fit-jersey", 2),
    colorImages: { "Grey": 0 },
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [{ name: "Grey", hex: "#9E9E9E" }],
    category: "Tanks",
  },
  {
    id: "airpods-case",
    name: "ProjectHandball AirPods Case",
    price: 15,
    description: "Rep the brand even when you're not on the court. Custom ProjectHandball AirPods case — the perfect accessory drop for the handball fan who has everything.",
    image: "/images/products/projecthandball-airpods-case/1.jpg",
    images: gallery("projecthandball-airpods-case", 8),
    colorImages: { "Pink": 0, "Mint": 2, "Navy": 4, "Black": 6 },
    sizes: ["One Size"],
    colors: [
      { name: "Pink",  hex: "#FFA0B4" },
      { name: "Mint",  hex: "#98E8A0" },
      { name: "Navy",  hex: "#1F2A4A" },
      { name: "Black", hex: "#1A1A1A" },
    ],
    category: "Accessories",
    isNew: true,
  },
];

export function getProduct(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getRelatedProducts(id: string, limit = 4): Product[] {
  const product = products.find(p => p.id === id);
  const sameCategory = products.filter(p => p.id !== id && p.category === product?.category);
  const others = products.filter(p => p.id !== id && p.category !== product?.category);
  return [...sameCategory, ...others].slice(0, limit);
}
